# Generated by Django 3.0.5 on 2020-04-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20200414_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image2',
            field=models.ImageField(null=True, upload_to='images3/'),
        ),
    ]
