# Generated by Django 3.0.5 on 2020-04-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='image2',
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
