# Generated by Django 3.0.5 on 2020-04-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20200414_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
