# Generated by Django 3.0.5 on 2020-04-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=50)),
                ('blog_pub_date', models.DateField()),
                ('blog_body', models.CharField(max_length=200)),
                ('blog_image', models.ImageField(upload_to='blogs/')),
            ],
        ),
    ]
