# Generated by Django 3.0.5 on 2020-04-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_pub_date',
            field=models.DateTimeField(),
        ),
    ]
