# Generated by Django 3.0.5 on 2020-04-15 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200415_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_pub_date',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='blog_title',
            new_name='title',
        ),
    ]
